name: mygfwlist

on: 
  push:
    branches: 
      - master
    paths:
      - 'add*.ini'


jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: checkout actions
        uses: actions/checkout@v2.3.4

      - name: run.sh
        run: curl -s "https://raw.githubusercontent.com/tanst/mygfwlist/master/run.sh" | sudo bash


      - name: commit
        run: |
            git config --global user.email t@tanst.net
            git config --global user.name tanst
            git add .
            git commit -m "update mygfwlist" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
